variables:

  KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
  KEYCLOAK_REST_ADAPTER_CLIENT_SECRET: ${KEYCLOAK_REST_ADAPTER_CLIENT_SECRET}
  NAMESPACE_DEV: test-keycloak-rest-adapter
  NAMESPACE_QA: keycloak-rest-adapter-qa
  NAMESPACE_PROD: keycloak-rest-adapter
  OPENSHIFT_SERVER_PROD: https://openshift.cern.ch
  OPENSHIFT_SERVER_DEV: https://openshift-dev.cern.ch
  BUILD_ENV_DEV: staging
  BUILD_ENV_PROD: production
  BUILD_ENV_QA: qa
  QA_TAG: qa
  DEV_TAG: dev
  RESOURCE: ${CI_PROJECT_NAME}

stages:
  - build_docker
  - test
  - deploy

.docker_build_template: &docker_definition
  stage: build_docker
  tags:
    - docker-image-build
  script: "echo building $CI_REGISTRY_IMAGE for keycloak-rest-adapter" # No empty scripts are allowed

.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  script:
    - oc import-image gitlab-registry.cern.ch/${CI_PROJECT_PATH}:${TAG} --confirm --token=${TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE}

build_docker_dev:
  <<: *docker_definition
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${DEV_TAG}
  only:
    - dev 

build_docker_qa:
  <<: *docker_definition
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${QA_TAG}
  only:
    - master

build_docker_prod:
  <<: *docker_definition
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - tags # the branch you want to publish

test:
  stage: test
  script:
    - 'echo "Tests not implemented..."'

.base_deploy: &base_deploy
  stage: deploy_image
  image: gitlab-registry.cern.ch/paas-tools/openshift-client
  script:
    - oc import-image ${RESOURCE}:${CI_COMMIT_TAG:-latest} --confirm --token=${TOKEN} --server=${SERVER} -n ${NAMESPACE}
    - oc process --local -f openshift/adapter_configmap.yaml -p KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD  -p KEYCLOAK_REST_ADAPTER_CLIENT_SECRET=$KEYCLOAK_REST_ADAPTER_CLIENT_SECRET | oc replace -f - --token=${TOKEN} --server=${SERVER} -n ${NAMESPACE}
    - oc tag --reference-policy=local --source=docker  ${CI_REGISTRY_IMAGE}:${OO_TAG} ${RESOURCE}:${OO_TAG} --token=${TOKEN} --server=${SERVER} -n ${NAMESPACE}

deploy_dev:
  <<: *deploy_definition
  variables:
    TOKEN: ${OPENSHIFT_DEV_TOKEN}
    OPENSHIFT_SERVER: ${OPENSHIFT_SERVER_DEV}
    NAMESPACE: ${NAMESPACE_DEV}
    TAG: ${DEV_TAG}
  environment:
    name: staging
    url: https://test-keycloak-rest-adapter.web.cern.ch
  only:
    - dev

deploy_qa:
  <<: *deploy_definition
  variables:
    TOKEN: ${OPENSHIFT_QA_TOKEN}
    OPENSHIFT_SERVER: ${OPENSHIFT_SERVER_PROD}
    NAMESPACE: ${NAMESPACE_QA}
    TAG: ${QA_TAG}
  environment:
    name: qa
    url: https://keycloak-rest-adapter-qa.web.cern.ch
  only:
    - master

deploy_prod:
  <<: *deploy_definition
  variables:
    TOKEN: ${OPENSHIFT_PROD_TOKEN}
    OPENSHIFT_SERVER: ${OPENSHIFT_SERVER_PROD}
    NAMESPACE: ${NAMESPACE_PROD}
    TAG: ${CI_COMMIT_TAG}
  environment:
    name: production
    url: https://keycloak-rest-adapter.web.cern.ch
  only:
    - tags
