variables:
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
  KEYCLOAK_REST_ADAPTER_CLIENTID: keycloak-rest-adapter
  KEYCLOAK_REST_ADAPTER_CLIENTID_SECRET: ${KEYCLOAK_REST_ADAPTER_CLIENT_SECRET}
  NAMESPACE_DEV: test-keycloak-rest-adapter
  NAMESPACE_QA: keycloak-rest-adapter-qa
  NAMESPACE_PROD: keycloak-rest-adapter
  KEYCLOAK_SERVER_PROD: https://keycloak.cern.ch
  KEYCLOAK_SERVER_QA: https://keycloak-qa.cern.ch
  KEYCLOAK_SERVER_DEV: https://keycloak-dev.cern.ch
  KEYCLOAK_REALM_PROD: master
  KEYCLOAK_REALM_QA: master
  KEYCLOAK_REALM_DEV: cern
  OPENSHIFT_SERVER_PROD: https://openshift.cern.ch
  OPENSHIFT_SERVER_DEV: https://openshift-dev.cern.ch
  BUILD_ENV_DEV: staging
  BUILD_ENV_PROD: production
  BUILD_ENV_QA: qa
  QA_TAG: qa
  DEV_TAG: dev
  RESOURCE: ${CI_PROJECT_NAME}
  APP_NAME: ${CI_PROJECT_NAME}
  ROUTE_HOSTNAME_PROD: https://${NAMESPACE_PROD}.web.cern.ch
  ROUTE_HOSTNAME_QA: https://${NAMESPACE_QA}.web.cern.ch
  ROUTE_HOSTNAME_DEV: https://${NAMESPACE_DEV}.web.cern.ch

stages:
  - test
  - build_docker
  - deploy

.docker_build_template: &docker_definition
  stage: build_docker
  tags:
    - docker-image-build
  script: "echo building $CI_REGISTRY_IMAGE for keycloak-rest-adapter" # No empty scripts are allowed

.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  script:
    - LOWERCASE_PATH=$(echo ${CI_PROJECT_PATH} | awk '{ print tolower($0) } ')
    # Adding || true to disable the error message when the image already exists
    - oc import-image ${APP_NAME} --from="gitlab-registry.cern.ch/${LOWERCASE_PATH}:${TAG}" --confirm --token=${TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE} || true
    - oc process --local -f openshift/adapter_configmap.yaml -p KEYCLOAK_SERVER=$KEYCLOAK_SERVER -p KEYCLOAK_REALM=$KEYCLOAK_REALM -p KEYCLOAK_ADMIN_USERNAME=$KEYCLOAK_ADMIN_USERNAME -p KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD -p KEYCLOAK_REST_ADAPTER_CLIENTID=$KEYCLOAK_REST_ADAPTER_CLIENTID -p KEYCLOAK_REST_ADAPTER_CLIENTID_SECRET=$KEYCLOAK_REST_ADAPTER_CLIENTID_SECRET -p ROUTE_HOSTNAME=$ROUTE_HOSTNAME | oc replace -f - --token=${TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE}
    - oc tag "gitlab-registry.cern.ch/${LOWERCASE_PATH}:${TAG}" "${APP_NAME}:latest" --token=${TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE}

### Testing

test:
  stage: test
  image: "python:3.7-alpine"
  before_script:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
  script:
    - pytest
  services:
    - name: gitlab-registry.cern.ch/authzsvc/docker-images/keycloak
      alias: keycloak
  variables:
    KEYCLOAK_USER: "admin"
    KEYCLOAK_PASSWORD: "admin"


### Docker build definitions

build_docker_dev:
  <<: *docker_definition
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${DEV_TAG}
  only:
    - dev

build_docker_qa:
  <<: *docker_definition
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${QA_TAG}
  only:
    - master

build_docker_prod:
  <<: *docker_definition
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - tags # the branch you want to publish

### Deployment definitions

deploy_dev:
  <<: *deploy_definition
  variables:
    KEYCLOAK_SERVER: ${KEYCLOAK_SERVER_DEV}
    KEYCLOAK_REALM: ${KEYCLOAK_REALM_DEV}
    KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD_DEV}
    ENVIRONMENT: dev
    OPENSHIFT_SERVER: ${OPENSHIFT_SERVER_DEV}
    TOKEN: ${OPENSHIFT_DEV_TOKEN}
    NAMESPACE: ${NAMESPACE_DEV}
    TAG: ${DEV_TAG}
    ROUTE_HOSTNAME: ${ROUTE_HOSTNAME_DEV}
  environment:
    name: staging
    url: https://test-keycloak-rest-adapter.web.cern.ch
  only:
    - dev

deploy_qa:
  <<: *deploy_definition
  variables:
    KEYCLOAK_SERVER: ${KEYCLOAK_SERVER_QA}
    KEYCLOAK_REALM: ${KEYCLOAK_REALM_QA}
    KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD_QA}
    ENVIRONMENT: qa
    TOKEN: ${OPENSHIFT_QA_TOKEN}
    OPENSHIFT_SERVER: ${OPENSHIFT_SERVER_PROD}
    NAMESPACE: ${NAMESPACE_QA}
    TAG: ${QA_TAG}
    ROUTE_HOSTNAME: ${ROUTE_HOSTNAME_QA}
  environment:
    name: qa
    url: https://keycloak-rest-adapter-qa.web.cern.ch
  only:
    - master

deploy_prod:
  <<: *deploy_definition
  variables:
    KEYCLOAK_SERVER: ${KEYCLOAK_SERVER_PROD}
    KEYCLOAK_REALM: ${KEYCLOAK_REALM_PROD}
    KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD_PROD}
    ENVIRONMENT: prod
    TOKEN: ${OPENSHIFT_PROD_TOKEN}
    OPENSHIFT_SERVER: ${OPENSHIFT_SERVER_PROD}
    NAMESPACE: ${NAMESPACE_PROD}
    TAG: ${CI_COMMIT_TAG}
    ROUTE_HOSTNAME: ${ROUTE_HOSTNAME_PROD}
  environment:
    name: production
    url: https://keycloak-rest-adapter.web.cern.ch
  only:
    - tags
