repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: deps-check
        name: deps-check
        entry: bash -c 'PIP_CONFIG_FILE=pip.conf pip-compile --quiet'
        language: system
        types: [file]
        files: ^requirements.*$
        pass_filenames: true
