language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - export PIP_CONFIG_FILE=$(pwd)/pip.conf
  - pip install -r requirements.txt -r dev-requirements.txt # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage
