apiVersion: v1
Kind: Template
metadata:
  name: keycloak-rest-adapter-template-configmap

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: keycloak-rest-adapter-configuration
    name: keycloak-rest-adapter-configmap

  data:
    client_saml_defaults.json: |-
      {
        "protocolMappers":[]
        "consentRequired": false
      }
    client_openid_defaults.json: |-
      {
        "protocolMappers":[],
        "webOrigins": ["+"],
        "consentRequired": false
      }
    keycloak_client.cfg : |
      [keycloak]
      server = ${KC_ALIAS}
      realm = ${REALM}
      keycloak_rest_adapter_client = ${CLIENT_ID}
      keycloak_rest_adapter_client_secret = ${CLIENT_SECRET}

      [oauth]
      redirect_url=${ROUTE_HOSTNAME}/oauth2-redirect.html
      https_swagger=true

      [oidc]
      jwks_url = ${KC_ALIAS}/auth/realms/cern/protocol/openid-connect/certs
      issuer =${KC_ALIAS}/auth/realms/cern

    auth_protocols.json: |
      {
        "saml": "definition",
        "openid": "clientId"
      }


parameters:
  - name: KC_ALIAS
    description: "Keycloak server alias"
    required: True
  - name: REALM
    description: "Keycloak REALM the REST adapter will interact with"
    value: 'master'
    required: True
  - name: CLIENT_ID
    description: "Client ID with rights over Keycloak Admin REST API"
    value: 'keycloak-rest-adapter'
    required: True
  - name: CLIENT_SECRET
    description: "Client secret"
    required: True
  - name: REDIRECT_URIS
    description: "Redirect URIS separated by commas"
    value: 'something.cern.ch'
  - name: ROUTE_HOSTNAME
    description: Openshift Route Hostname
