apiVersion: v1
Kind: Template
metadata:
  name: keycloak-rest-adapter-template-configmap

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: keycloak-rest-adapter-cfg
      name: keycloak-rest-adapter-cfg

    data:
      overrides.py: |-
        KEYCLOAK_SERVER = "${KC_ALIAS}"


        KEYCLOAK_REALM = "${REALM}"
        KEYCLOAK_CLIENT_SECRET = "${CLIENT_SECRET}"
        KEYCLOAK_CLIENT_ID = "${CLIENT_ID}"

        OAUTH_AUTH_URL = "${KC_ALIAS}/auth/realms/cern/protocol/openid-connect/auth"

        OIDC_JWKS_URL = "${KC_ALIAS}/auth/realms/cern/protocol/openid-connect/certs"
        OIDC_ISSUER = "${KC_ALIAS}/auth/realms/cern"

        OAUTH_HTTPS_SWAGGER = True
        SWAGGER_UI_OAUTH_REDIRECT_URL = "${ROUTE_HOSTNAME}/oauth2-redirect.html"

        LOG_DIR = "/var/log/keycloak-rest-adapter/"

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: keycloak-rest-adapter-cfg
      name: keycloak-rest-adapter-env

    data:
      KEYCLOAK_REST_ADAPTER_CONFIG: /opt/config/overrides.py


parameters:
  - name: KC_ALIAS
    description: "Keycloak server alias"
    required: True
  - name: REALM
    description: "Keycloak REALM the REST adapter will interact with"
    value: 'master'
    required: True
  - name: CLIENT_ID
    description: "Client ID with rights over Keycloak Admin REST API"
    value: 'keycloak-rest-adapter'
    required: True
  - name: CLIENT_SECRET
    description: "Client secret"
    required: True
  - name: ROUTE_HOSTNAME
    description: Openshift Route Hostname
