---
  kind: "Template"
  apiVersion: "v1"
  metadata:
    name: "keycloak-rest-adapter-configuration"
    creationTimestamp: null
    annotations:
      description: "Keycloak Rest Adapter application configuration OpenShift template."
      tags: "keycloak-rest-adapter-configuration"
  labels:
    template: "keycloak-rest-adapter-application"
  objects:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name:  keycloak-rest-adapter-configmap
      data:
        flask_oidc_config.json: |
          {
              "web": {
                  "issuer": "https://${KEYCLOAK_SERVER}/auth/realms/master",
                  "auth_uri": "https://${KEYCLOAK_SERVER}/auth/realms/master/protocol/openid-connect/auth",
                  "client_id": "${CLIENT_ID}",
                  "client_secret": "${CLIENT_SECRET}",
                  "redirect_uris": [
                      "${REDIRECT_URIS}"
                  ],
                  "bearer_only": "true",
                  "token_uri": "https://${KEYCLOAK_SERVER}/auth/realms/master/protocol/openid-connect/token",
                  "token_introspection_uri": "https://${KEYCLOAK_SERVER}/auth/realms/master/protocol/openid-connect/token/introspect"
              }
          }

        keycloak_client.cfg : |
          [keycloak]
          server = ${KEYCLOAK_SERVER}
          realm = ${KEYCLOAK_REALM}
          admin_user = ${KEYCLOAK_ADMIN_USERNAME}
          admin_password = ${KEYCLOAK_ADMIN_USERNAME_PASSWORD}
          keycloak-rest-adapter-client = ${KEYCLOAK_REST_ADAPTER_CLIENTID}
          keycloak-rest-adapter-client-secret = ${KEYCLOAK_REST_ADAPTER_CLIENTID_SECRET}
          ssl_cert_path = /etc/pki/tls/certs/CERN-bundle.pem


  parameters:
    - name: KEYCLOAK_SERVER
      description: "Keycloak FQDN server"
      value: 'keycloak-dev-01.cern.ch'
      required: True
    - name: KEYCLOAK_REALM
      description: "Keycloak REALM"
      value: 'master'
      required: True
    - name: KEYCLOAK_ADMIN_USERNAME
      description: "Username with admin rights over Keycloak"
      value: 'admin'
      required: True
    - name: KEYCLOAK_ADMIN_USERNAME_PASSWORD
      description: "Password of the user with admin rights over Keycloak"
      value: 'password'
      required: True
    - name: KEYCLOAK_REST_ADAPTER_CLIENTID
      description: "Client ID of the client"
      value: 'keycloak-rest-adapter'
      required: True
    - name: KEYCLOAK_REST_ADAPTER_CLIENTID_SECRET
      description: "Secret of the client ID"
      value: 'a2ea1c8d-9387-XXXX-YYYY-AAAAAAAAA'
      required: True
    - name: SSL_CERT_PATH
      description: "Path to the SSl certificate"
      value: '/etc/pki/tls/certs/CERN-bundle.pem'
      required: True
    - name: CLIENT_ID
      description: "Keycloak client_id of the client for the OIDC configuration"
      value: 'authorization-service-api-dev-danielfr'
      required: True
    - name: CLIENT_SECRET
      description: "Keycloak secret of the client for the OIDC configuration"
      value: 'supersecret'
      required: True
    - name: REDIRECT_URIS
      description: "Redirect URIS separated by commas"
      value: 'something.cern.ch'
